# Generated by Django 3.2.15 on 2022-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
