# Generated by Django 3.2.13 on 2022-08-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='errors',
            field=models.JSONField(null=True, verbose_name='错误信息: Dict'),
        ),
    ]
