# Generated by Django 3.2.13 on 2022-08-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0007_auto_20220807_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='trigger_mode',
            field=models.JSONField(default=list, verbose_name='机器人触发方式: List[int]'),
        ),
    ]
