# Generated by Django 3.2.13 on 2022-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0010_auto_20220807_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='errors',
        ),
        migrations.AddField(
            model_name='components',
            name='running_msg',
            field=models.JSONField(default=dict, verbose_name='运行信息: Dict'),
        ),
        migrations.AlterField(
            model_name='components',
            name='component_role',
            field=models.IntegerField(choices=[(1, 'Messenger'), (2, 'Processor')], default=1, verbose_name='组件角色'),
        ),
    ]
