# Generated by Django 3.2.13 on 2022-08-14 10:11

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_auto_20220807_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot2function',
            name='command_args',
            field=models.JSONField(default=list, encoder=json.encoder.JSONEncoder, verbose_name='触发命令的参数: List[Dict]'),
        ),
    ]
