# Generated by Django 3.2.13 on 2022-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0015_alter_robot2function_command_args'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='last_report_time',
        ),
        migrations.AddField(
            model_name='components',
            name='last_report_time',
            field=models.DateTimeField(null=True, verbose_name='最近健康报告时间'),
        ),
    ]
