# Generated by Django 3.2.15 on 2022-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_auto_20220814_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functions',
            name='comment',
        ),
        migrations.AddField(
            model_name='functions',
            name='explain',
            field=models.CharField(max_length=2048, null=True, verbose_name='功能说明'),
        ),
    ]
