# Generated by Django 3.2.15 on 2022-08-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0017_auto_20220819_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='last_report_time',
            field=models.DateTimeField(null=True, verbose_name='最新报告时间'),
        ),
    ]
