# Generated by Django 3.2.15 on 2022-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_alter_components_last_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='last_report_time',
            field=models.DateTimeField(null=True, verbose_name='最近报告时间'),
        ),
    ]
