# Generated by Django 3.2.15 on 2022-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0019_alter_components_last_report_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='run_time',
        ),
        migrations.AddField(
            model_name='robots',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='启用时间'),
        ),
    ]
