# Generated by Django 3.2.15 on 2022-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0021_auto_20220825_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='components',
            name='last_report_time',
            field=models.DateTimeField(null=True, verbose_name='最近报告时间'),
        ),
        migrations.AlterField(
            model_name='functions',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='robots',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='启用时间'),
        ),
    ]
