# Generated by Django 3.2.15 on 2022-09-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0022_auto_20220825_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RobotMeta',
        ),
    ]
