# Generated by Django 3.2.15 on 2022-09-22 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot', '0023_delete_robotmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingFunctions',
            fields=[
                ('timing_function_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='定时任务功能ID')),
                ('timing_function_name', models.CharField(max_length=32, verbose_name='功能名称')),
                ('timing_function_url', models.CharField(max_length=255, verbose_name='功能路径')),
                ('timing_function_class', models.CharField(max_length=32, null=True, verbose_name='功能分类')),
                ('global_function_status', models.IntegerField(choices=[(0, '停用'), (1, '启用')], default=1, verbose_name='功能状态')),
                ('default_function_config', models.JSONField(default=list, verbose_name='默认定时任务功能配置: List[Dict]')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('explain', models.CharField(max_length=2048, null=True, verbose_name='定时功能说明')),
            ],
            options={
                'verbose_name_plural': '机器人功能表',
                'db_table': 'timing_functions',
            },
        ),
        migrations.CreateModel(
            name='Robot2TimingFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_status', models.IntegerField(choices=[(0, '停用'), (1, '启用')], default=1, verbose_name='功能状态')),
                ('timing_cron', models.CharField(max_length=255, verbose_name='定时任务时间')),
                ('timing_function_config', models.JSONField(default=dict, verbose_name='定时任务功能配置: Dict')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.robots', to_field='robot_id')),
                ('timing_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.timingfunctions')),
            ],
            options={
                'verbose_name_plural': '机器人与定时任务关系表',
                'db_table': 'robot2timing',
                'unique_together': {('admin_user_id', 'robot_id', 'timing_function_id')},
            },
        ),
    ]
