# Generated by Django 3.2.15 on 2022-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0024_robot2timingfunction_timingfunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingfunctions',
            name='default_timing_cron',
            field=models.CharField(default=1, max_length=255, verbose_name='默认定时时间'),
            preserve_default=False,
        ),
    ]
