# Generated by Django 3.2.15 on 2022-09-26 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot', '0026_auto_20220923_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Robot2TimingFunction',
            new_name='Robot2Timing',
        ),
    ]
