# Generated by Django 3.2.15 on 2022-09-26 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robot', '0028_alter_robot2timing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='robot2timing',
            unique_together={('admin_user_id', 'robot_id', 'timing_function_id')},
        ),
    ]
